export const FETCH_POSTS = 'FETCH_POSTS'
export const NEW_POST = 'NEW_POST'

export const GET_MOVIES = 'GET_MOVIES'
export const GET_MOVIE_BY_ID = 'GET_MOVIE_BY_ID'
export const EDIT_MOVIE = 'EDIT_MOVIE'
export const ADD_MOVIE = 'ADD_MOVIE'
export const DELETE_MOVIE = 'DELETE_MOVIE'

export const USER_SIGN_IN = 'USER_SIGN_IN'
export const USER_LOG_IN = 'USER_LOG_IN'
export const USER_LOG_OUT = 'USER_LOG_OUT'
export const USER_VERIFY = 'USER_VERIFY'
export const USER_GET_MOVIES = 'USER_GET_MOVIES'
export const USER_GET = 'USER_GET'
export const USER_ADD_MOVIE = 'USER_ADD_MOVIE'
export const FILTER = 'FILTER'